name: Siri Shortcut

on: repository_dispatch  

jobs:
  update-readmed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo Received: ${{github.event.client_payload.description}}
          echo "# ${{github.event.client_payload.description}}" > ./README.md        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README via Siri shortcut
